version: '3.1'
services:
  easylinker:
    restart: always
    image: registry.cn-shenzhen.aliyuncs.com/thunk/easylinker-open:3.0.0
    container_name: easylinker
    ports:
    - 2500:2500
    - 1884:1884
